name: Deploy to VPS

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS SSH host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH key for authentication
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/projects/Full_Stack/Javascript/SocialHub/socialhub-backend
            git pull

            export API_GATEWAY_PORT=${{ secrets.API_GATEWAY_PORT }}
            export IDENTITY_SERVICE_PORT=${{ secrets.IDENTITY_SERVICE_PORT }}
            export POST_SERVICE_PORT=${{ secrets.POST_SERVICE_PORT }}
            export MEDIA_SERVICE_PORT=${{ secrets.MEDIA_SERVICE_PORT }}
            export SEARCH_SERVICE_PORT=${{ secrets.SEARCH_SERVICE_PORT }}
            export IDENTITY_SERVICE_URL=${{ secrets.IDENTITY_SERVICE_URL }}
            export POST_SERVICE_URL=${{ secrets.POST_SERVICE_URL }}
            export MEDIA_SERVICE_URL=${{ secrets.MEDIA_SERVICE_URL }}
            export SEARCH_SERVICE_URL=${{ secrets.SEARCH_SERVICE_URL }}
            export REDIS_DB=${{ secrets.REDIS_DB }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_URL=${{ secrets.REDIS_URL }}
            export RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export MONGODB_URI=${{ secrets.MONGODB_URI }}
            export CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            export CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            export CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            export CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}
            export REDIS_PREFIX_API_GATEWAY=${{ secrets.REDIS_PREFIX_API_GATEWAY }}
            export REDIS_PREFIX_IDENTITY_SERVICE=${{ secrets.REDIS_PREFIX_IDENTITY_SERVICE }}
            export REDIS_PREFIX_POST_SERVICE=${{ secrets.REDIS_PREFIX_POST_SERVICE }}
            export REDIS_PREFIX_MEDIA_SERVICE=${{ secrets.REDIS_PREFIX_MEDIA_SERVICE }}
            export REDIS_PREFIX_SEARCH_SERVICE=${{ secrets.REDIS_PREFIX_SEARCH_SERVICE }}


            docker-compose down
            docker-compose up -d

      
      - name: Debug SSH connection (optional)
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"
        continue-on-error: true